services:
  web:
    container_name: studentblog-web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - api
    networks:
      - studentblog-net

  api:
    container_name: studentblog-api
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - studentblog-net
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=studentblog-db;Port=5432;Database=StudentBlog;Username=admin;Password=StUdentBl0g_db;
      - JWT__Key=Not_A_Real_Password_Was_Randomly_Generated_For_This_Project_Mosaic_Quantum_Game_Rancidity_Darkish_Darkroom_Dazzling_Swapping1_Spokesman;
      - JWT__Issuer=http://localhost:8080;
      - JWT__Audience=http://localhost:8080;
    
  database:
    container_name: studentblog-db
    image: postgres:17
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: StUdentBl0g_db
      POSTGRES_DB: StudentBlog
    networks:
      - studentblog-net
    volumes:
    - studentblog-volume:/var/lib/postgresql/data

networks:
  studentblog-net:
    driver: bridge

volumes:
  studentblog-volume: