services:
  web:
    container_name: studentblog-web
    build:
      context: ./nginx
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "81:81"
    depends_on:
      - api
    networks:
      - studentblog-net

  api:
    container_name: studentblog-api
    build:
      context: ./Server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    networks:
      - studentblog-net
    env_file: ".env"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__PostgresConnection=Host=studentblog-db;Port=5432;Database=${DATABASE};Username=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - JWT__Key=${JWT_KEY}
      - JWT__Issuer=https://localhost:81/api/auth/;
      - JWT__Audience=https://localhost:81/api/;
    
  database:
    container_name: studentblog-db
    image: postgres:17
    ports:
      - "5432:5432"
    env_file: ".env"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${DATABASE}
    networks:
      - studentblog-net
    volumes:
    - studentblog-volume:/var/lib/postgresql/data

networks:
  studentblog-net:
    driver: bridge

volumes:
  studentblog-volume:
